---
- name: "Upstream | Execute the role and catch errors"
  block:
    - name: "Upstream | Include selinux role"
      ansible.builtin.include_role:
        name: fedora.linux_system_roles.selinux
      vars:
        selinux_state: "{{ system_selinux_state | d(omit) }}"
        selinux_policy: "{{ system_selinux_policy | d(omit) }}"
        selinux_booleans: "{{ system_selinux_booleans | d([]) }}"
        selinux_fcontexts: "{{ system_selinux_fcontexts | d([]) }}"
        selinux_logins: "{{ system_selinux_logins | d([]) }}"
        selinux_ports: "{{ system_selinux_ports | d([]) }}"
        selinux_restore_dirs: "{{ system_selinux_restore_dirs | d([]) }}"
        selinux_all_purge: "{{ system_selinux_all_purge | d(false) }}"
        selinux_booleans_purge: "{{ system_selinux_booleans_purge | d(false) }}"
        selinux_fcontexts_purge: "{{ system_selinux_fcontexts_purge | d(false) }}"
        selinux_ports_purge: "{{ system_selinux_ports_purge | d(false) }}"
        selinux_logins_purge: "{{ system_selinux_logins_purge | d(false) }}"

  rescue:
    # Fail if failed for a different reason than system_selinux_reboot_required.
    - name: "Upstream | Handle errors"
      ansible.builtin.fail:
        msg: "Include role fedora.linux_system_roles.selinux failed"
      when: not system_selinux_reboot

    - name: "Upstream | Restart managed host"
      ansible.builtin.reboot:
      when: system_selinux_reboot

    - name: "Upstream | Wait for managed host to come back"
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 300

    - name: "Upstream | Reapply the role"
      ansible.builtin.include_role:
        name: fedora.linux_system_roles.selinux
      vars:
        selinux_state: "{{ system_selinux_state | d(omit) }}"
        selinux_policy: "{{ system_selinux_policy | d(omit) }}"
        selinux_booleans: "{{ system_selinux_booleans | d(omit) }}"
        selinux_fcontexts: "{{ system_selinux_fcontexts | d(omit) }}"
        selinux_logins: "{{ system_selinux_logins | d(omit) }}"
        selinux_ports: "{{ system_selinux_ports | d(omit) }}"
        selinux_restore_dirs: "{{ system_selinux_restore_dirs | d(omit) }}"
        selinux_all_purge: "{{ system_selinux_all_purge | d(omit) }}"
        selinux_booleans_purge: "{{ system_selinux_booleans_purge | d(omit) }}"
        selinux_fcontexts_purge: "{{ system_selinux_fcontexts_purge | d(omit) }}"
        selinux_ports_purge: "{{ system_selinux_ports_purge | d(omit) }}"
        selinux_logins_purge: "{{ system_selinux_logins_purge | d(omit) }}"

...
