---
galaxy_info:
  author: MTO79
  role_name: system_motd
  description: Configure MOTD (Message of the day) on your system.
  license: MIT
  min_ansible_version: "2.11.0"
  standalone: true

  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - mto79
    - system
    - linux
    - motd

dependencies: []

...
