---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-yaml
        files: .*\.(yaml|yml)$
        args: [--unsafe]
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-xml
      - id: check-toml
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: check-added-large-files

  - repo: https://github.com/ansible/ansible-lint.git
    rev: v6.8.2
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
