---
- name: "Reload firewall"
  ansible.builtin.service:
    name: "{{ system_firewall_service }}"
    state: reloaded
  when:
    - ansible_connection not in [ "container", "docker", "community.docker.docker" ]
    - not ansible_check_mode | bool

- name: "Reload firewalld"
  ansible.builtin.command: firewall-cmd --reload
  register: _system_firewall_reload_result
  changed_when: _system_firewall_reload_result.rc != 0

...
