---
- name: "Reboot"
  ansible.builtin.reboot:
    msg: "Rebooting ..."
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
  become: true

- name: "Restart dnf"
  ansible.builtin.command:
    cmd: "dnf clean all"
  changed_when: false
  listen: "Restart dnf"
  become: true

...
