---
- name: "Reboot"
  ansible.builtin.reboot:
    msg: "Rebooting for transparent_hugepage change"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
  become: true

...
