---
- name: "Setup | display message"
  ansible.builtin.debug:
    msg: "Setup selinux for {{ ansible_facts.os_family }}"

- name: "Setup | execute the role and catch errors"
  block:
    - name: "Setup | include selinux role" 
      ansible.builtin.include_role:
          name: fedora.linux_system_roles.selinux
     
  rescue:
    # Fail if failed for a different reason than selinux_reboot_required.
    - name: "Setup | handle errors"
      ansible.builtin.fail:
        msg: "role failed"
      when: not selinux_reboot_required

    - name: "Setup | restart managed host" 
      ansible.builtin.reboot:
      when:
         - core_selinux_reboot 

    - name: "Setup | wait for managed host to come back"
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 300

    - name: "Setup | reapply the role"
      ansible.builtin.include_role:
        name: fedora.linux_system_roles.selinux

...
