---
_system_motd_setup_update_scripts:
  - 00-header
  - 10-help-text
  - 50-landscape-sysinfo
  - 50-motd-news
  - 85-fwupd
  - 88-esm-announce
  - 91-contract-ua-esm-status
  - 91-release-upgrade
  - 92-unattended-upgrades
  - 95-hwe-eol
  - 97-overlayroot
  - 98-fsck-at-reboot
  - 98-reboot-required

...
