---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: "Check if connection still works"
      ansible.builtin.ping:

    - name: "Check if AllowUsers is set"
      ansible.builtin.lineinfile:
        path: "/etc/ssh/sshd_config"
        line: "AllowUsers root"
      check_mode: true
      register: "_system_sshd_setup_check_if_allowusers_is_set"
      failed_when:
        - _system_sshd_setup_check_if_allowusers_is_set is changed

    - name: "Check if AllowGroups is set"
      ansible.builtin.lineinfile:
        path: "/etc/ssh/sshd_config"
        line: "AllowGroups root"
      check_mode: true
      register: "_system_sshd_check_if_allowgroups_is_set"
      failed_when:
        - _system_sshd_check_if_allowgroups_is_set is changed

...
