---
- name: "Setup | Install requirements sysctl"
  ansible.builtin.package:
    name: "{{ system_sysctl_setup_packages }}"
    state: "present"
  become: true

- name: "Setup | Set sysctl setting"
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: "{{ system_sysctl_setup_set }}"
    state: "present"
    reload: "{{ system_sysctl_setup_reload }}"
  loop: "{{ system_sysctl_setup_items }}"
  when:
    - system_sysctl_setup_items is defined
    - item.name is defined
    - item.value is defined
    - ansible_connection not in [ "container", "docker", "community.docker.docker" ]
  loop_control:
    label: "{{ item.name }}"
  become: true

...
