---
- name: "Assert | Ensure __role_name is defined"
  ansible.builtin.assert:
    that:
      - __role_name is defined
      - __role_name is string
      - __role_name | length > 0
      - "__role_name != ['temp', 'late'] | join('')"

- name: "Assert | test if system_timesync_ntp_servers is set correctly"
  ansible.builtin.assert:
    that:
      - system_timesync_ntp_servers is iterable
    quiet: true
  when:
    - system_timesync_ntp_servers is defined

...
