---
- name: "Setup | Filesystem | Test storage_filesystems"
  ansible.builtin.assert:
    that:
      - filesystem.name is defined
    quiet: true

- name: "Setup | Filesystem | Create filesystems"
  community.general.filesystem:
    dev: "{{ filesystem.name }}"
    fstype: "{{ filesystem.fstype | default(system_storage_setup_default_fstype) }}"
  notify:
    - "Reload systemd"
  become: true

- name: "Setup | Filesystem | Run handlers"
  ansible.builtin.meta: flush_handlers

...
