---
- name: "Setup | Partition | Test partition"
  ansible.builtin.assert:
    that:
      - partition.name is defined
      - partition.number is defined
      - partition.part_start is defined or
        partition.part_end is defined
    quiet: true

- name: "Setup | Partition | Test partition.label"
  ansible.builtin.assert:
    that:
      - partition.label is defined
      - partition.label is iterable
      - partition.label in [ "aix", "amiga", "bsd", "dvh", "gpt", "loop", "mac", "msdos", "pc98", "sun" ]
    quiet: true
  when:
    - partition.label is defined

- name: "Setup | Partition | Rescan device"
  become: true
  block:
    - name: "Setup | Partition | Rescan device"
      ansible.builtin.lineinfile:
        path: "{{ partition.name }}"
        line: "1"
  rescue:
    - name: "Setup | Partition | Inform user"
      ansible.builtin.debug:
        msg: "Rescanning causes a freeze, lets continue"

- name: "Setup | Partition | Create partitions"
  community.general.parted:
    device: "{{ partition.name }}"
    number: "{{ partition.number }}"
    flags: "{{ partition.flags | default(omit) }}"
    part_start: "{{ partition.part_start | default(omit) }}"
    part_end: "{{ partition.part_end | default(omit) }}"
    label: "{{ partition.label | default(omit) }}"
    state: present
  become: true

...
