---
- name: "Setup | Volume | Test volume"
  ansible.builtin.assert:
    that:
      - volume.name is defined
      - volume.vg is defined
      - volume.size is defined
    quiet: true

- name: "Setup | Volume | Create logical volume"
  community.general.lvol:
    lv: "{{ volume.name }}"
    vg: "{{ volume.vg }}"
    size: "{{ volume.size }}"
    opts: "{{ volume.opts | default(omit) }}"
  notify:
    - "Run vgscan --mknodes"
  become: true

- name: "Setup | Volume | Run handlers"
  ansible.builtin.meta: flush_handlers

...
