---
galaxy_info:
  author: MTO79
  role_name: system_cups
  description: Role to manage cups
  license: MIT
  min_ansible_version: "2.11.0"
  standalone: true

  platforms: []

  galaxy_tags:
    - mto79
    - system
    - linux
    - cups
    - print
    - printer
    - printing

dependencies: []

...
