---
system_sshd_setup_packages:
   - "openssh-server"

system_sshd_setup_key_types:
  - "rsa"
  - "ecdsa"
  - "ed25519"

system_sshd_setup_run_directory: "/run/sshd"

system_sshd_setup_configuration_file: /etc/ssh/"sshd_config"

_system_sshd_setup_service:
  default: "sshd"
  Debian-bullseye: "ssh"
  Ubuntu-19: "ssh"
  Ubuntu-20: "ssh"

system_sshd_setup_service: >
  {{ _system_sshd_setup_service[ansible_facts['distribution'] ~ '-' ~ ansible_facts['distribution_release']] |
  default(_system_sshd_setup_service['default'] ) }}

system_sshd_setup_template_src: "sshd_config_debian.j2"

system_sshd_setup_template_mode: "644"

system_sshd_setup_sftp_server: "/usr/lib/openssh/sftp-server"

...
