---
system_sshd_setup_packages:
  - "openssh-server"

system_sshd_setup_key_types:
  - "rsa"
  - "ecdsa"
  - "ed25519"

system_sshd_setup_run_directory: "/run/sshd"

system_sshd_setup_configuration_file: /etc/ssh/sshd_config"

system_sshd_setup_service: "sshd"

system_sshd_setup_template_src: "sshd_config_redhat-7.j2"

system_sshd_setup_template_mode: "600"

system_sshd_setup_sftp_server: "/usr/libexec/openssh/sftp-server"

...
