---
- name: "Upstream | Execute the role and catch errors"
  become: true
  block:

    - name: "Upstream | Include timesync role"
      ansible.builtin.include_role:
        name: "fedora.linux_system_roles.timesync"
      vars:
        timesync_ntp_servers: "{{ system_timesync_upstream_ntp_servers | d([]) }}"
        timesync_ptp_domains: "{{ system_timesync_upstream_ptp_domains | d([]) }}"
        timesync_dhcp_ntp_servers: "{{ system_timesync_upstream_dhcp_ntp_servers | d(false) }}"
        timesync_step_threshold: "{{ system_timesync_upstream_step_threshold | d(-1.0) }}"
        timesync_min_sources: "{{ system_timesync_upstream_min_sources | d(1) }}"
        timesync_ntp_hwts_interfaces: "{{ system_timesync_upstream_ntp_hwts_interfaces | d([]) }}"
        timesync_ntp_provider: "{{ system_timesync_upstream_ntp_provider | d('chrony') }}"
        timesync_max_distance: "{{ system_timesync_upstream_max_distance | d(0) }}"

  rescue:

    - name: "Upstream | Handle errors"
      ansible.builtin.fail:
        msg: "Include fedora.linux_system_roles.timesync role failed"

...
