---
- name: "Setup | Execute the role and catch errors"
  block:
    - name: "Setup | Place template /etc/motd (message of the day)"
      ansible.builtin.template:
        src: templates/motd.j2
        dest: /etc/motd
        mode: "0444"

  rescue:
    - name: "Setup | Handle errors"
      ansible.builtin.fail:
        msg: "MOTD Role failed"
...
