---
- name: "Upstream | Execute the role and catch errors"
  block:
    - name: "Upstream | Include network role"
      ansible.builtin.include_role:
        name: "fedora.linux_system_roles.network"
      vars:
        network_connections: "{{ system_network_upstream_connections | default([]) }}"

  rescue:
    - name: "Upstream | Handle errors"
      ansible.builtin.fail:
        msg: "Include fedora.linux_system_roles.network role failed"

...
