---
system_samba_setup_ :
  - "smb"
  - "winbind"

system_samba_setup_packages:
  - "samba"
  - "samba-client"
  - "samba-common"
  - "cifs-utils"
  - "sssd-winbind-idmap"

system_samba_setup_selinux_booleans:
  - { name: 'samba_domain_controller', state: 'on', persistent: 'yes' }
  - { name: 'samba_export_all_ro', state: 'on', persistent: 'yes' }
  - { name: 'samba_export_all_rw', state: 'on', persistent: 'yes' }

system_samba_setup_firewall_ :
  - { zone: "public", service: "samba", state: "enabled", permanent: true, immediate: true }

...
