---
- name: "Setup | Install packages"
  ansible.builtin.package:
    name: "{{ system_cups_setup_packages }}"
    state: present

- name: "Setup | Configure cups"
  ansible.builtin.template:
    src: templates/setup/cupsd.conf.j2
    dest: /etc/cups/cupsd.conf
    mode: "0640"
    validate: cupsd -t -c %s
  notify:
    - Restart cups

- name: "Setup | Start and enable software"
  ansible.builtin.service:
    name: "{{ system_cups_setup_service }}"
    state: started
    enabled: true
  when:
    - system_cups_setup_service is defined

...
