---
- name: "Setup | Install requirements"
  ansible.builtin.package:
    name: "{{ system_hostname_setup_requirements }}"
    state: "present"
  become: true

- name: "Setup | Display hostname"
  ansible.builtin.debug:
    msg: "Hostname: {{ system_hostname_setup_hostname }}"

- name: "Setup | Set hostname"
  ansible.builtin.hostname:
    name: "{{ system_hostname_setup_hostname }}"
  notify:
    - "Reboot"
    - "Gather facts"
  when:
    - ansible_connection not in [ "container", "docker", "community.docker.docker" ]
  become: true

...
