---
- name: "Setup | Install openssh"
  ansible.builtin.package:
    name: "{{ system_sshd_setup_packages }}"
    state: "present"
  become: true

- name: "Setup | Configure selinux to allow openssh_port"
  community.general.seport:
    ports: "{{ system_sshd_setup_port }}"
    proto: "tcp"
    setype: "ssh_port_t"
    state: "present"
  when:
    - ansible_facts['ansible_selinux']['status'] is defined
    - ansible_facts['ansible_selinux']['status'] == "enabled"
  become: true

- name: "Setup | Generate host key"
  ansible.builtin.command:
    cmd: "/usr/bin/ssh-keygen -q -t {{ item }} -f /etc/ssh/ssh_host_{{ item }}_key -C '' -N ''"
    creates: "/etc/ssh/ssh_host_{{ item }}_key"
  loop: "{{ system_sshd_setup_key_types }}"
  become: true

- name: "Setup | Make run directory"
  ansible.builtin.file:
    path: "{{ system_sshd_setup_run_directory }}"
    state: directory
    mode: "0755"
  when:
    - ansible_facts['os_family'] == "Debian"
  become: true

- name: "Setup | Configure openssh"
  ansible.builtin.template:
    dest: "templates/setup/{{ system_sshd_setup_configuration_file }}"
    src: "{{ system_sshd_setup_template_src }}"
    mode: "{{ system_sshd_setup_template_mode }}"
    owner: "root"
    group: "root"
    validate: "sshd -f %s -t"
  notify:
    - "Restart openssh"
  become: true

- name: "Setup | Start and enable openssh"
  ansible.builtin.service:
    name: "{{ system_sshd_setup_service }}"
    state: "started"
    enabled: true
  become: true

- name: "Flush handlers"
  ansible.builtin.meta: "flush_handlers"

...
