---
- name: "Setup | install required software"
  ansible.builtin.package:
    name: "{{ core_users_requirements }}"
    state: present

- name: "Setup | loop over core_users_group_list"
  ansible.builtin.include_tasks:
    file: "group.yml"
  loop: "{{ core_users_group_list }}"
  loop_control:
    label: "{{ group.name }}"
    loop_var: group
  when:
    - core_users_group_list is defined

- name: "Setup | loop over core_users_user_list"
  ansible.builtin.include_tasks:
    file: user.yml
  loop: "{{ core_users_user_list }}"
  loop_control:
    label: "{{ user.name }}"
    loop_var: user
  when:
    - core_users_user_list is defined

- name: "Setup | manage cron permission"
  ansible.builtin.template:
    src: cron.allow.j2
    dest: /etc/cron.allow
    mode: "0644"
  when:
    - core_users_cron_allow|bool

- name: "Setup | check existence of /etc/cron.allow"
  ansible.builtin.file:
    path: /etc/cron.allow
    state: absent
  when:
    - not core_users_cron_allow | bool

...
