---
- name: "User | create local ssh_key_directory"
  ansible.builtin.file:
    path: "{{ core_users_ssh_key_directory }}"
    state: directory
    mode: "0750"
  when:
    - user.manage_ssh_key is defined
    - user.manage_ssh_key | bool
  delegate_to: localhost
  become: false

- name: "User | Salt and Hash password user when set in attributes."
  ansible.builtin.set_fact:
    user_password_hash: "{{ user.password | string | password_hash('sha512', (core_users_password_salt | string)) }}"
  when:
    - user.password is defined
    - user.password | length > 0

- name: "User | manage users {{ user.name }}"
  ansible.builtin.user:
    name: "{{ user.name }}"
    state: "{{ user.state | default('present') }}"
    comment: "{{ user.comment | default(omit) }}"
    create_home: "{{ core_users_create_home }}"
    password: "{{ user_password_hash | default(omit) }}"
    uid: "{{ user.uid | default(omit) }}"
    group: "{{ user.group | default(omit) }}"
    groups: "{{ user.groups | default(omit) }}"
    home: "{{ user.home | default(omit) }}"
    shell: "{{ user.shell | default(core_users_shell) }}"
    update_password: "{{ user.update_password | default(omit) }}"
    expires: "{{ user.expires | default(omit) }}"
    system: "{{ user.system | default(omit) }}"
  register: core_users_manage_user

- name: "User | set sudo options for {{ user.name }}"
  ansible.builtin.template:
    src: sudo_user.j2
    dest: '/etc/sudoers.d/{{ user.name | replace(".", "dot") }}_user'
    mode: "0640"
    validate: /usr/sbin/visudo -cf %s
  when:
    - user.sudo_options is defined
  loop_control:
    label: "{{ user.name }}"

- name: "User | remove sudo options for {{ user.name }}"
  ansible.builtin.file:
    path: '/etc/sudoers.d/{{ user.name | replace(".", "dot") }}_user'
    state: absent
  when:
    - user.sudo_options is not defined
  loop_control:
    label: "{{ user.name }}"

- name: "User | ensure the sudoers.d directory is checked for user sudoers files (will be put after EOF if not exists)"
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    line: '#includedir /etc/sudoers.d'

- name: "User | generate private ssh key for {{ user.name }}"
  ansible.builtin.command:
    cmd: "{{ core_users_ssh_keygen_command }}"
    creates: "{{ core_users_ssh_key_directory }}/{{ user.name }}"
  when:
    - user.manage_ssh_key is defined
    - user.manage_ssh_key | bool
  loop_control:
    label: "{{ user.name }}"
  delegate_to: localhost
  become: false

- name: "User | generate public ssh key for {{ user.name }}"
  ansible.builtin.shell:
    cmd: "{{ core_users_ssh_keygen_pubkey_command }} > {{ core_users_ssh_key_directory }}/{{ user.name }}.pub"
    creates: "{{ core_users_ssh_key_directory }}/{{ user.name }}.pub"
  when:
    - user.manage_ssh_key is defined
    - user.manage_ssh_key | bool
  loop_control:
    label: "{{ user.name }}"
  delegate_to: localhost
  become: false

- name: "User | convert ssh key to ppk for {{ user.name }}"
  ansible.builtin.shell:
    cmd: >
           ssh-keygen -e -f "{{ core_users_ssh_key_directory }}/{{ user.name }}"
           -C "Generated by Ansible"
           > "{{ users_ssh_key_directory }}/{{ user.name }}.ppk"
    creates: "{{ users_ssh_key_directory }}/{{ user.name }}.ppk"
  when:
    - user.manage_ssh_key is defined
    - user.manage_ssh_key | bool
  delegate_to: localhost
  become: false

- name: "User | create .ssh directory for {{ user.name }}"
  ansible.builtin.file:
    path: "/home/{{ user.name }}/.ssh"
    state: directory
    mode: "700"
  become: true
  become_user: "{{ user.name }}"
  when:
    - user.manage_ssh_key is defined
    - user.manage_ssh_key

- name: "User | deploy authorized keys for {{ user.name }}"
  ansible.posix.authorized_key:
    user: "{{ user.name }}"
    state: present
    key: "{{ item }}"
  loop: "{{ user.authorized_keys }}"
  loop_control:
    label: "{{ user.name }}"
  when:
    - user.authorized_keys is defined

- name: "User | remove unauthorized keys for {{ user.name }}"
  ansible.posix.authorized_key:
    user: "{{ user.name }}"
    state: absent
    key: "{{ item }}"
  loop: "{{ user.unauthorized_keys }}"
  loop_control:
    label: "{{ user.name }}"
  when:
    - user.unauthorized_keys is defined

- name: "User | copy generated private ssh key for {{ user.name }}"
  ansible.builtin.copy:
    src: "{{ core_users_ssh_key_directory }}/{{ user.name }}"
    dest: "/home/{{ user.name }}/.ssh/id_rsa"
    mode: "400"
    owner: "{{ user.name }}"
    group: "{{ user.group | default(omit) }}"
  when:
    - core_users_manage_user is defined
    - user.copy_private_key is defined
    - user.copy_private_key | bool
  loop_control:
    label: "{{ user.name }}"

- name: "User | check users password valid time"
  ansible.builtin.command:
    cmd: awk 'BEGIN { FS = ":" } $1 == "{{ user.name }}" { print $5 }' /etc/shadow
  register: core_users_pw_valid
  changed_when: false
  check_mode: false
  when:
    - user.state is defined and user.state != "absent" or
      user.state is not defined

- name: "User | set users password valid time"
  ansible.builtin.command:
    cmd: chage -M "{{ user.password_validity_days }}" "{{ user.name }}"
  when:
    - user.password_validity_days is defined
    - core_users_pw_valid.stdout is defined
    - core_users_pw_valid.stdout | int !=  user.password_validity_days | int

...
