---
- name: "Setup | Include build tasks."
  ansible.builtin.include_tasks: "build.yml"
  when: "system_kernel_setup_build | bool"

- name: "Setup | Manage grub."
  when: "system_kernel_setup_grub | bool"
  become: true
  block:

    - name: "Setup | Add transparent_hugepage=never to GRUB_CMDLINE_LINUX"
      ansible.builtin.lineinfile:
        path: "/etc/default/grub"
        regexp: '^GRUB_CMDLINE_LINUX='
        line: 'GRUB_CMDLINE_LINUX="quiet splash transparent_hugepage=never"'
        backrefs: true

    - name: "Setup | Update GRUB"
      ansible.builtin.command: "update-grub"
      changed_when: false
      notify:
        - "Reboot"

...
