---
- name: "Setup | One kernel | Remove older kernels, keeping the latest one"
  become: true
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: "absent"
  loop: "{{ _system_kernel_setup_installed_kernels.stdout_lines }}"
  when: "item != _system_kernel_setup_latest_kernel"

- name: "Setup | Remove old kernel packages"
  become: true
  ansible.builtin.command: "dnf remove --oldinstallonly -y"
  changed_when: false

- name: "Setup | One kernel | Update bootloader"
  ansible.builtin.include_tasks: "bootloader.yml"

...
