---
- name: "Setup | Include build tasks."
  ansible.builtin.include_tasks: "build.yml"
  when: "system_kernel_setup_build | bool"

- name: "Setup | Set installonly_limit in /etc/dnf/dnf.conf"
  ansible.builtin.lineinfile:
    path: "/etc/dnf/dnf.conf"
    regexp: "^installonly_limit="
    line: "installonly_limit={{ system_kernel_setup_installonly_limit }}"
    state: "present"
  notify:
    - "Restart dnf"

- name: "Setup | Keep only one kernel"
  ansible.builtin.include_tasks: "one_kernel.yml"
  when: "system_kernel_setup_keep_one_kernel | bool"

- name: "Setup | Manage grub."
  become: true
  block:

    - name: "Setup | Disable Transparent Hugepages on all kernels"
      ansible.builtin.command: "grubby --update-kernel=/boot/vmlinuz-$(uname -r) --args='transparent_hugepage=never'"
      when: "system_kernel_setup_grub_hugepage | bool"
      changed_when: false

    - name: "Setup | Grubby for rd.auto"
      ansible.builtin.command: "grubby --update-kernel=/boot/vmlinuz-$(uname -r) --args=rd.auto"
      when: "system_kernel_setup_grub_rdauto | bool"
      changed_when: false

...
