---
- name: "Setup | Install packages cron"
  ansible.builtin.package:
    name: "{{ system_cron_setup_packages }}"
    state: "present"
  become: true

- name: "Setup | Configure shell"
  ansible.builtin.lineinfile:
    path: "{{ system_cron_setup_configuration }}"
    line: "SHELL={{ system_cron_setup_shell }}"
    regexp: "^SHELL"
    create: true
    mode: "0600"
  notify:
    - "Restart cron"
  become: true

- name: "Setup | Configure path"
  ansible.builtin.lineinfile:
    path: "{{ system_cron_setup_configuration }}"
    line: "PATH={{ system_cron_setup_path }}"
    regexp: "^PATH"
    create: true
    mode: "0600"
  notify:
    - "Restart cron"
  become: true

- name: "Setup | Configure mailto"
  ansible.builtin.lineinfile:
    path: "{{ system_cron_setup_configuration }}"
    line: "MAILTO={{ system_cron_setup_mailto }}"
    regexp: "^MAILTO"
    create: true
    mode: "0600"
  notify:
    - "Restart cron"
  become: true

- name: "Setup | Start and enable cron"
  ansible.builtin.service:
    name: "{{ system_cron_setup_service }}"
    state: "started"
    enabled: true
  when:
    - system_cron_setup_service is defined
    - system_cron_setup_service | length
  become: true

- name: "Setup | Schedule requested cron jobs"
  ansible.builtin.cron:
    name: "{{ item.name }}"
    minute: "{{ item.minute | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    day: "{{ item.day | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
    weekday: "{{ item.weekday | default(omit) }}"
    special_time: "{{ item.special_time | default(omit) }}"
    job: "{{ item.job }}"
    state: "{{ item.state | default('present') }}"
    user: "{{ item.user | default(omit) }}"
  loop: "{{ system_cron_setup_jobs }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - system_cron_setup_jobs is defined
  become: true

...
