---
- name: "Upstream | Execute the vendor role and catch errors"
  block:
    - name: "Upstream | Include vendor firewall role"
      ansible.builtin.include_role:
        name: fedora.linux_system_roles.firewall
      vars:
        firewall: "{{ system_firewall | d([]) }}"

  rescue:
    - name: "Upstream | Handle errors"
      ansible.builtin.fail:
        msg: "Include fedora.linux_system_roles.firewall role failed"

...
