---
- name: "Setup | Install chrony package"
  ansible.builtin.apt:
    name: chrony
    state: present

- name: "Setup | Start and enable chrony package"
  ansible.builtin.service:
    name: chrony
    state: started
    enabled: true

- name: "Setup | Configure chrony"
  ansible.builtin.template:
    src: templates/debian/chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart chrony

...
