---
- name: "Setup | Execute the role and catch errors"
  block:
    - name: "Setup | include kernel_settings role"
      ansible.builtin.include_role:
        name: fedora.linux_system_roles.timesync

  rescue:
    - name: "Setup | Handle errors"
      ansible.builtin.fail:
        msg: "Include fedora.linux_system_roles.timesync role failed"

...
