---
- name: "Reload systemd"
  when: ansible_service_mgr == 'systemd'
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: "Run vgscan --mknodes"
  ansible.builtin.command:
    cmd: vgscan --mknodes
  changed_when: true
  become: true

- name: "Refresh facts"
  ansible.builtin.setup:

...
