---
system_epel_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm"
system_epel_gpg_key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9"
system_epel_next_url: "https://dl.fedoraproject.org/pub/epel/epel-next-release-latest-9.noarch.rpm"

...
