---
- name: "Setup | pam_mkhomedir | Insert new rule pam_mkhomedir.so in common-session for AD home directories"
  community.general.pamd:
    name: "common-session"
    type: "session"
    control: "optional"
    module_path: "pam_systemd.so"
    new_type: "session"
    new_control: "required"
    new_module_path: "pam_mkhomedir.so"
    module_arguments: "skel=/etc/skel umask=0022"
    state: "after"

...
