---
- name: "Setup | Redhat 8 | Install packages for joining AD"
  ansible.builtin.dnf:
    name: "{{ system_ad_integration_setup_packages }}"
    state: present
    update_cache: true

- name: "Setup | Redhat 8 | PIP for pexpect"
  ansible.builtin.include_tasks:
    file: "setup/pexpect.yml"
  when: system_ad_integration_setup_pexpect_use

- name: "Setup | Redhat 8 | Register"
  ansible.builtin.include_tasks:
    file: "setup/register.yml"
  when: system_ad_integration_setup_register

- name: "Setup | Redhat 8 | Register"
  ansible.builtin.include_tasks:
    file: "setup/unregister.yml"
  when: not system_ad_integration_setup_register

- name: "Setup | Redhat 8 | Configuring sssd.conf"
  ansible.builtin.template:
    src: "templates/setup/sssd.j2"
    dest: "/etc/sssd/sssd.conf"
    owner: "root"
    group: "root"
    mode: "0600"

- name: "Setup | Redhat 8 | Configuring krb5.conf"
  ansible.builtin.template:
    src: "templates/setup/krb5.j2"
    dest: "/etc/krb5/krb5.conf"
    owner: "root"
    group: "root"
    mode: "0600"

- name: "Setup | Redhat 8 | Clear SSSD"
  ansible.builtin.include_tasks:
    file: "setup/clear_sssd.yml"
  when: system_ad_integration_setup_clear_sssd

- name: "Setup | Redhat 8 | Create new pam_mkhomedir.so rule"
  ansible.builtin.include_tasks:
    file: "setup/pam_mkhomedir.yml"
  when: system_ad_integration_setup_pam_mkhomedir

...
