---
- name: "Setup | Execute the vendor role and catch errors"
  when:
    - system_firewall_vendor is defined
    - system_firewall_vendor | bool
  block:
    - name: "Setup | Include vendor firewall role"
      ansible.builtin.include_role:
        name: fedora.linux_system_roles.firewall
      vars:
        firewall: "{{ system_firewall | d([]) }}"

  rescue:
    - name: "Setup | Handle errors"
      ansible.builtin.fail:
        msg: "Include fedora.linux_system_roles.firewall role failed"

# - name: "Setup | Execute the custom role and catch errors"
#   when:
#     - system_firewall_vendor is defined
#     - not system_firewall_vendor | bool == true
#   block:
    # - name: "Setup | Include firewall custom role"
    #   ansible.builtin.include_task:
    #     name: "firewalld.yml"
    #   vars:
    #     firewall: "{{ system_firewall | d([]) }}"

#  rescue:
#    - name: "Setup | Handle errors"
#      ansible.builtin.fail:
#        msg: "Include custom role failed"

...
