---
system_kernel_setup_unarchive_src: "https://cdn.kernel.org/pub/linux/kernel/v{{ system_kernel_setup_version[:1] }}.x/linux-{{ system_kernel_setup_version }}.tar.xz"

system_kernel_setup_unarchive_creates: "{{ system_kernel_setup_build_location }}/linux-{{ system_kernel_setup_version }}"

system_kernel_setup_requirements:
  - "bison"
  - "flex"
  - "hostname"
  - "libelf-devel"
  - "openssl-devel"

system_kernel_setup_modules_location: "/lib/modules/{{ system_kernel_setup_version }}*"

system_kernel_setup_installation_location: "/boot/vmlinuz"

...
