---
- name: "Upstream | Execute the role and catch errors"
  block:
    - name: "Setup | Include rhc role"
      ansible.builtin.include_role:
        name: fedora.linux_system_roles.rhc
      vars:
        rhc_state: "{{ system_rhc_upstream_state | d('present') }}"
        rhc_auth: "{{ system_rhc_upstream_auth | d({}) }}"
        rhc_baseurl: "{{ system_rhc_upstream_baseurl | d(omit) }}"
        rhc_environments: "{{ system_rhc_upstream_environments | d([]) }}"
        rhc_insights: "{{ system_rhc_upstream_insights | d(omit) }}"
        rhc_organization: "{{ system_rhc_upstream_organization | d(omit) }}"
        rhc_proxy: "{{ system_rhc_upstream_proxy | d(omit) }}"
        rhc_release: "{{ system_rhc_upstream_release | d(omit) }}"
        rhc_repositories: "{{ system_rhc_upstream_repositories | d(omit) }}"
        rhc_server: "{{ system_rhc_upstream_server | d(omit) }}"

  rescue:
    - name: "Upstream | Handle errors"
      ansible.builtin.fail:
        msg: "Include role fedora.linux_system_roles.rhc failed"

...
