---
- name: "Setup | Make sure dnf-utils is installed"
  ansible.builtin.dnf:
    name: dnf-utils
    state: installed

- name: "Setup | Ensure updated Setup - Security"
  when: system_update_security
  ansible.builtin.dnf:  # noqa: package-latest
    name: "*"
    state: latest
    security: true
    skip_broken: true
  register: system_update_security_result
  failed_when: system_update_security_result.rc != 0

- name: "Setup | Ensure updated Setup - Bugfix"
  when: system_update_bugfix
  ansible.builtin.dnf:  # noqa: package-latest
    name: "*"
    state: latest
    bugfix: true
    skip_broken: true
  register: system_update_bugfix_result
  failed_when: system_update_bugfix_result.rc != 0

- name: "Setup | Ensure updated Setup - Setup only"
  when: system_update_release
  ansible.builtin.dnf:  # noqa: package-latest
    name: "*"
    state: latest
    update_only: true
    skip_broken: true
  register: system_update_release_result
  failed_when: system_update_release_result.rc != 0

- name: "Setup | Check if reboot is required"
  ansible.builtin.command: needs-restarting -r
  register: system_update_reboot_required
  ignore_errors: true
  changed_when: false

- name: "Setup | Display result if reboot is needed"
  ansible.builtin.debug:
    var: system_update_reboot_required.rc
  notify:
    - "Reboot after update"
  changed_when: system_update_reboot_required.rc == 1

- name: "Setup | Autoremove obsolete packages"
  ansible.builtin.dnf:
    autoremove: "{{ system_update_autoremove | default(true) }}"

...
