---
- name: "Assert | Ensure __role_name is defined"
  ansible.builtin.assert:
    that:
      - __role_name is defined
      - __role_name is string
      - __role_name | length > 0
      # Make sure you can't forget to replace the role name
      - "__role_name != ['temp', 'late'] | join('')"

- name: "Assert | Assert setup specific vars"
  when: __role_action == "setup"
  block:
    - name: "Assert | Test ssh_port"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_port is defined
          - system_sshd_setup_port is number
          - system_sshd_setup_port > 0
          - system_sshd_setup_port < 65536
        quiet: true

    - name: "Assert | Test system_sshd_setup_address_family"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_address_family is defined
          - system_sshd_setup_address_family is string
          - system_sshd_setup_address_family in [ "any", "inet", "inet6" ]
        quiet: true

    - name: "Assert | Test system_sshd_setup_listen_addresses"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_listen_addresses is defined
          - system_sshd_setup_listen_addresses is iterable
        quiet: true

    - name: "Assert | Test system_sshd_setup_host_keys"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_host_keys is defined
          - system_sshd_setup_host_keys is iterable
        quiet: true

    - name: "Assert | Test system_sshd_setup_rekey_limit"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_rekey_limit is defined
          - system_sshd_setup_rekey_limit is string
          - system_sshd_setup_rekey_limit is not none
        quiet: true

    - name: "Assert | Test system_sshd_setup_syslog_facility"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_syslog_facility is defined
          - system_sshd_setup_syslog_facility is string
          - system_sshd_setup_syslog_facility in [ "DAEMON", "USER", "AUTH", "LOCAL0", "LOCAL1", "LOCAL2", "LOCAL3", "LOCAL4", "LOCAL5", "LOCAL6", "LOCAL7" ]
        quiet: true

    - name: "Assert | Test system_sshd_setup_loglevel"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_loglevel is defined
          - system_sshd_setup_loglevel is string
          - system_sshd_setup_loglevel in [ "QUIET", "FATAL", "ERROR", "INFO", "VERBOSE", "DEBUG", "DEBUG1", "DEBUG2", "DEBUG3" ]
        quiet: true

    - name: "Assert | Test system_sshd_setup_login_grace_time"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_login_grace_time is defined
          - system_sshd_setup_login_grace_time is string
          - system_sshd_setup_login_grace_time is not none
        quiet: true

    - name: "Assert | Test system_sshd_setup_permit_root_login"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_permit_root_login is defined
          - system_sshd_setup_permit_root_login is string
          - system_sshd_setup_permit_root_login in [ "true", "no", "without-password", "prohibit-password", "forced-commands-only" ]
        quiet: true

    - name: "Assert | Test system_sshd_setup_strict_modes"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_strict_modes is defined
          - system_sshd_setup_strict_modes is string
          - system_sshd_setup_strict_modes in [ "true", "no" ]
        quiet: true

    - name: "Assert | Test system_sshd_setup_max_auth_tries"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_max_auth_tries is defined
          - system_sshd_setup_max_auth_tries is number
          - system_sshd_setup_max_auth_tries >= 0
        quiet: true

    - name: "Assert | Test system_sshd_setup_max_sessions"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_max_sessions is defined
          - system_sshd_setup_max_sessions is number
          - system_sshd_setup_max_sessions >= 0
        quiet: true

    - name: "Assert | Test system_sshd_setup_pub_key_authentication"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_pub_key_authentication is defined
          - system_sshd_setup_pub_key_authentication is string
          - system_sshd_setup_pub_key_authentication in [ "true", "no" ]
        quiet: true

    - name: "Assert | Test system_sshd_setup_authorized_key_file"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_authorized_key_file is defined
          - system_sshd_setup_authorized_key_file is string
          - system_sshd_setup_authorized_key_file is not none
        quiet: true

    - name: "Assert | Test system_sshd_setup_authorized_prinicpals_file"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_authorized_prinicpals_file is defined
          - system_sshd_setup_authorized_prinicpals_file is string
          - system_sshd_setup_authorized_prinicpals_file is not none
        quiet: true

    - name: "Assert | Test system_sshd_setup_authorized_keys_command"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_authorized_keys_command is defined
          - system_sshd_setup_authorized_keys_command is string
          - system_sshd_setup_authorized_keys_command is not none
        quiet: true

    - name: "Assert | Test system_sshd_setup_authorized_keys_command_user"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_authorized_keys_command_user is defined
          - system_sshd_setup_authorized_keys_command_user is string
          - system_sshd_setup_authorized_keys_command_user is not none
        quiet: true

    - name: "Assert | Test system_sshd_setup_host_based_authentication"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_host_based_authentication is defined
          - system_sshd_setup_host_based_authentication is string
          - system_sshd_setup_host_based_authentication in [ "true", "no" ]
        quiet: true

    - name: "Assert | Test system_sshd_setup_ignore_user_known_hosts"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_ignore_user_known_hosts is defined
          - system_sshd_setup_ignore_user_known_hosts is string
          - system_sshd_setup_ignore_user_known_hosts in [ "true", "no" ]
        quiet: true

    - name: "Assert | Test system_sshd_setup_ignore_rhosts"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_ignore_rhosts is defined
          - system_sshd_setup_ignore_rhosts is string
          - system_sshd_setup_ignore_rhosts in [ "true", "no" ]
        quiet: true

    - name: "Assert | Test system_sshd_setup_permit_empty_passwords"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_permit_empty_passwords is defined
          - system_sshd_setup_permit_empty_passwords is string
          - system_sshd_setup_permit_empty_passwords in [ "true", "no" ]
        quiet: true

    - name: "Assert | Test system_sshd_setup_password_authentication"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_password_authentication is defined
          - system_sshd_setup_password_authentication is string
          - system_sshd_setup_password_authentication in [ "true", "no" ]
        quiet: true

    - name: "Assert | Test system_sshd_setup_challenge_response_authentication"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_challenge_response_authentication is defined
          - system_sshd_setup_challenge_response_authentication is string
          - system_sshd_setup_challenge_response_authentication in [ "true", "no" ]
        quiet: true

    - name: "Assert | Test system_sshd_setup_gssapi_authentication"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_gssapi_authentication is defined
          - system_sshd_setup_gssapi_authentication is string
          - system_sshd_setup_gssapi_authentication in [ "true", "no" ]
        quiet: true

    - name: "Assert | Test system_sshd_setup_gssapi_cleanup_credentials"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_gssapi_cleanup_credentials is defined
          - system_sshd_setup_gssapi_cleanup_credentials is string
          - system_sshd_setup_gssapi_cleanup_credentials in [ "true", "no" ]
        quiet: true

    - name: "Assert | Test system_sshd_setup_gssapi_strict_acceptor_check"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_gssapi_strict_acceptor_check is defined
          - system_sshd_setup_gssapi_strict_acceptor_check is string
          - system_sshd_setup_gssapi_strict_acceptor_check in [ "true", "no" ]
        quiet: true

    - name: "Assert | Test system_sshd_setup_gssapi_key_exchange"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_gssapi_key_exchange is defined
          - system_sshd_setup_gssapi_key_exchange is string
          - system_sshd_setup_gssapi_key_exchange in [ "true", "no" ]
        quiet: true

    - name: "Assert | Test system_sshd_setup_gssaip_enable_k5_users"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_gssaip_enable_k5_users is defined
          - system_sshd_setup_gssaip_enable_k5_users is string
          - system_sshd_setup_gssaip_enable_k5_users in [ "true", "no" ]
        quiet: true

    - name: "Assert | Test system_sshd_setup_use_pam"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_use_pam is defined
          - system_sshd_setup_use_pam is string
          - system_sshd_setup_use_pam in [ "true", "no" ]
        quiet: true

    - name: "Assert | Test system_sshd_setup_allow_agent_forwarding"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_allow_agent_forwarding is defined
          - system_sshd_setup_allow_agent_forwarding is string
          - system_sshd_setup_allow_agent_forwarding in [ "true", "no" ]
        quiet: true

    - name: "Assert | Test system_sshd_setup_allow_tcp_forwarding"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_allow_tcp_forwarding is defined
          - system_sshd_setup_allow_tcp_forwarding is string
          - system_sshd_setup_allow_tcp_forwarding in [ "true", "no" ]
        quiet: true

    - name: "Assert | Test system_sshd_setup_gateway_ports"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_gateway_ports is defined
          - system_sshd_setup_gateway_ports is string
          - system_sshd_setup_gateway_ports in [ "true", "no" ]
        quiet: true

    - name: "Assert | Test system_sshd_setup_x11_forwarding"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_x11_forwarding is defined
          - system_sshd_setup_x11_forwarding is string
          - system_sshd_setup_x11_forwarding in [ "true", "no" ]
        quiet: true

    - name: "Assert | Test system_sshd_setup_x11_display_offset"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_x11_display_offset is defined
          - system_sshd_setup_x11_display_offset is number
          - system_sshd_setup_x11_display_offset > 0
        quiet: true

    - name: "Assert | Test system_sshd_setup_x11_use_localhost"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_x11_use_localhost is defined
          - system_sshd_setup_x11_use_localhost is string
          - system_sshd_setup_x11_use_localhost in [ "true", "no" ]
        quiet: true

    - name: "Assert | Test system_sshd_setup_permit_tty"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_permit_tty is defined
          - system_sshd_setup_permit_tty is string
          - system_sshd_setup_permit_tty in [ "true", "no" ]
        quiet: true

    - name: "Assert | Test system_sshd_setup_print_motd"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_print_motd is defined
          - system_sshd_setup_print_motd is string
          - system_sshd_setup_print_motd in [ "true", "no" ]
        quiet: true

    - name: "Assert | Test system_sshd_setup_print_last_log"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_print_last_log is defined
          - system_sshd_setup_print_last_log is string
          - system_sshd_setup_print_last_log in [ "true", "no" ]
        quiet: true

    - name: "Assert | Test system_sshd_setup_tcp_keep_alive"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_tcp_keep_alive is defined
          - system_sshd_setup_tcp_keep_alive is string
          - system_sshd_setup_tcp_keep_alive in [ "true", "no" ]
        quiet: true

    - name: "Assert | Test system_sshd_setup_permit_user_environment"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_permit_user_environment is defined
          - system_sshd_setup_permit_user_environment is string
          - system_sshd_setup_permit_user_environment in [ "true", "no" ]
        quiet: true

    - name: "Assert | Test system_sshd_setup_compression"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_compression is defined
          - system_sshd_setup_compression is string
          - system_sshd_setup_compression in [ "true", "no", "delayed" ]
        quiet: true

    - name: "Assert | Test system_sshd_setup_client_alive_interval"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_client_alive_interval is defined
          - system_sshd_setup_client_alive_interval is number
          - system_sshd_setup_client_alive_interval >= 0
        quiet: true

    - name: "Assert | Test system_sshd_setup_client_alive_count_max"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_client_alive_count_max is defined
          - system_sshd_setup_client_alive_count_max is number
          - system_sshd_setup_client_alive_count_max >= 0
        quiet: true

    - name: "Assert | Test system_sshd_setup_show_patch_level"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_show_patch_level is defined
          - system_sshd_setup_show_patch_level is string
          - system_sshd_setup_show_patch_level in [ "true", "no" ]
        quiet: true

    - name: "Assert | Test system_sshd_setup_use_dns"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_use_dns is defined
          - system_sshd_setup_use_dns is string
          - system_sshd_setup_use_dns in [ "true", "no" ]
        quiet: true

    - name: "Assert | Test system_sshd_setup_pid_file"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_pid_file is defined
          - system_sshd_setup_pid_file is string
          - system_sshd_setup_pid_file is not none
        quiet: true

    - name: "Assert | Test system_sshd_setup_max_startups"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_max_startups is defined
          - system_sshd_setup_max_startups is string
          - system_sshd_setup_max_startups is not none
        quiet: true

    - name: "Assert | Test system_sshd_setup_permit_tunnel"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_permit_tunnel is defined
          - system_sshd_setup_permit_tunnel is string
          - system_sshd_setup_permit_tunnel in [ "true", "no" ]
        quiet: true

    - name: "Assert | Test system_sshd_setup_chroot_directory"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_chroot_directory is defined
          - system_sshd_setup_chroot_directory is string
          - system_sshd_setup_chroot_directory is not none
        quiet: true

    - name: "Assert | Test system_sshd_setup_version_addendum"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_version_addendum is defined
          - system_sshd_setup_version_addendum is string
          - system_sshd_setup_version_addendum is not none
        quiet: true

    - name: "Assert | Test system_sshd_setup_banner"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_banner is defined
          - system_sshd_setup_banner is string
          - system_sshd_setup_banner is not none
        quiet: true

    - name: "Assert | Test system_sshd_setup_accept_envs"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_accept_envs is defined
          - system_sshd_setup_accept_envs is iterable
        quiet: true

    - name: "Assert | Test system_sshd_setup_subsystem"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_subsystem is defined
          - system_sshd_setup_subsystem is string
          - system_sshd_setup_subsystem is not none
        quiet: true

    - name: "Assert | Test system_sshd_setup_trusted_user_ca_keys"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_trusted_user_ca_keys is defined
          - system_sshd_setup_trusted_user_ca_keys is string
          - system_sshd_setup_trusted_user_ca_keys is not none
        quiet: true

    - name: "Assert | Test system_sshd_setup_allow_users"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_allow_users is iterable
        quiet: true
      when:
        - system_sshd_setup_allow_users is defined

    - name: "Assert | Test system_sshd_setup_allow_groups"
      ansible.builtin.assert:
        that:
          - system_sshd_setup_allow_groups is iterable
        quiet: true
      when:
        - system_sshd_setup_allow_groups is defined


- name: "Assert | Assert setup specific vars"
  when: __role_action == "upstream"
  block:
    - name: "Assert | Test system_sshd_upstream_ssh"
      ansible.builtin.assert:
        that:
          - system_sshd_upstream_ssh is iterable
        quiet: true
      when:
        - system_sshd_upstream_ssh is defined

...
