---
- name: "Assert | Assert upstream specific vars"
  when: __role_action == "upstream"
  block:
    - name: "Assert | Test if system_firewall is set correctly"
      ansible.builtin.assert:
        that:
          - system_firewall is defined
          - system_firewall is iterable
          - system_firewall | length > 0
        quiet: true

...
