---
- name: "Assert | Assert platform/version specific variables"
  ansible.builtin.include_tasks:
    file: "default.yml"
  when: __role_action_task == "setup"

- name: "Assert | Assert vendor specific vars"
  when: __role_action_task == "upstream"
  block:
    - name: "Assert | Test if system_firewall is set correctly"
      ansible.builtin.assert:
        that:
          - system_firewall is defined
          - system_firewall is iterable
          - system_firewall | length > 0
      quiet: true

...
