---
- name: "Assert | test if system_selinux_role_name is set correctly"
  ansible.builtin.assert:
    that:
      - system_selinux_role_name is defined
      - system_selinux_role_name is string
      - system_selinux_role_name in ["system_selinux"]   
    quiet: true

- name: "Assert | test if system_selinux_state is set correctly"
  ansible.builtin.assert:
    that:
      - system_selinux_state is defined
      - system_selinux_state is string
      - system_selinux_state in [ "disabled", "enforcing", "permissive" ]
    quiet: true

- name: "Assert | test if system_selinux_policy is set correctly"
  ansible.builtin.assert:
    that:
      - system_selinux_policy is defined
      - system_selinux_policy is string
      - system_selinux_policy in [ "default", "minimum", "mls", "targeted" ]
    quiet: true

...
