---
- name: "Assert | test if selinux_state is set correctly"
  ansible.builtin.assert:
    that:
      - selinux_state is defined
      - selinux_state is string
      - selinux_state in [ "disabled", "enforcing", "permissive" ]
    quiet: true

- name: "Assert | test if selinux_policy is set correctly"
  ansible.builtin.assert:
    that:
      - selinux_policy is defined
      - selinux_policy is string
      - selinux_policy in [ "default", "minimum", "mls", "targeted" ]
    quiet: true

...
