---
- name: "Setup | Display timezone"
  ansible.builtin.debug:
    msg: "Timezone: {{ system_timezone_setup_timezone }}"

- name: "Setup | Set timezone"
  community.general.timezone:
    name: "{{ system_timezone_setup_timezone }}"
  become: true

...
