---
- name: "Setup | Automatic | Install dnf-automatic package"
  ansible.builtin.package:
    name: "{{ system_dnf_setup_automatic_package }}"
    state: "present"
  become: true

- name: "Setup | Automatic | Deploy dnf-automatic configuration file"
  ansible.builtin.template:
    src: "templates/setup/automatic.conf.j2"
    dest: "/etc/dnf/automatic.conf"
    mode: "0644"
  become: true

- name: "Setup | Automatic | Perform auto reboot specific tasks"
  become: true
  when: "system_dnf_setup_automatic_reboot | bool"
  block:

    - name: "Setup | Automatic | Install dependencies needed for reboot"
      ansible.builtin.package:
        name: "{{ system_dnf_automatic_reboot_dependencies }}"
        state: "present"

    - name: "Setup | Automatic | Deploy service and timer units"
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "/etc/systemd/system/{{ item }}"
        owner: "root"
        group: "root"
        mode: "0644"
      loop:
        - "dnf-automatic-reboot.service"
        - "dnf-automatic-reboot.timer"
      notify: "Reload systemd"

- name: "Setup | Automatic | Check status of dnf-automatic-install.timer"
  ansible.builtin.systemd:
    name: "dnf-automatic-install.timer"
  register: "_system_dnf_setup_automatic_install_timer"

- name: "Setup | Automatic | Start and enable systemd timer for dnf-automatic"
  ansible.builtin.service:
    name: "dnf-automatic-install.timer"
    state: "started"
    enabled: true
  # run always if not in check mode or if the timer unit exists
  # regardless of the check mode state
  when: "not ansible_check_mode or
        _system_dnf_setup_automatic_install_timer.status['LoadState'] == 'loaded'"
  become: true

- name: "Setup | Automatic | Check status of dnf-automatic-reboot.timer"
  ansible.builtin.systemd:
    name: "dnf-automatic-reboot.timer"
  register: "_system_dnf_setup_automatic_reboot_timer"

- name: "Setup | Automatic | Set timer state for auto reboot"
  ansible.builtin.systemd:
    name: "dnf-automatic-reboot.timer"
    state: "{{ system_dnf_setup_automatic_reboot | ternary('started', 'stopped') }}"
    enabled: "{{ system_dnf_setup_automatic_reboot }}"
    masked: false
  # run always if not in check mode and the auto reboot is enabled
  # or if the timer unit exists regardless of the check mode state
  when: "(not ansible_check_mode and dnf_automatic_reboot) or
        _system_dnf_setup_automatic_reboot_timer.status['LoadState'] == 'loaded'"
  become: true

...
