---
- name: "Setup | Include versionlock tasks."
  ansible.builtin.include_tasks: "redhat/versionlock.yml"
  when: system_dnf_setup_versionlock_use | bool

- name: "Setup | Include automatic tasks."
  ansible.builtin.include_tasks: "redhat/automatic.yml"
  when: system_dnf_setup_automatic_use | bool

...
