---
- name: "Setup | Include versionlock tasks."
  include_tasks: "versionlock.yml"
  when: system_dnf_setup_versionlock_use | bool

- name: "Setup | Include automatic tasks."
  include_tasks: "automatic.yml"
  when: system_dnf_setup_automatic_use | bool

...
