---
- name: "Assert | Ensure __role_name is defined"
  ansible.builtin.assert:
    that:
      - "__role_name is defined"
      - "__role_name is string"
      - "__role_name | length > 0"
      # Make sure you can't forget to replace the role name
      - "__role_name != ['temp', 'late'] | join('')"

- name: "Assert | Setup specific vars"
  when: __role_action == "setup"
  block:

    - name: "Assert | Test if system_users_setup_ssh_key_directory is set correctly"
      ansible.builtin.assert:
        that:
          - "system_users_setup_ssh_key_directory is defined"
          - "system_users_setup_ssh_key_directory is string"
        quiet: true

    - name: "Assert | Test if system_users_setup_shell is set correctly"
      ansible.builtin.assert:
        that:
          - "system_users_setup_shell is defined"
          - "system_users_setup_shell is string"
        quiet: true

    - name: "Assert | Test if system_users_setup_cron_allow is set correctly"
      ansible.builtin.assert:
        that:
          - "system_users_setup_cron_allow is defined"
          - "system_users_setup_cron_allow is boolean"
        quiet: true

    - name: "Assert | Test if system_users_setup_create_home is set correctly"
      ansible.builtin.assert:
        that:
          - "system_users_setup_create_home is defined"
          - "system_users_setup_create_home is boolean"
        quiet: true

    - name: "Assert | Test if system_users_setup_group_list is set correctly"
      ansible.builtin.assert:
        that:
          -" system_users_setup_group_list is iterable"
        quiet: true
      when:
        - "system_users_setup_group_list is defined"

    - name: "Assert | Test if item.name in system_users_setup_group_list is set correctly"
      ansible.builtin.assert:
        that:
          - "item.name is defined"
          - "item.name is string"
        quiet: true
      loop: "{{ system_users_setup_group_list }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - "system_users_setup_group_list is defined"

    - name: "Assert | Test if item.gid in system_users_setup_group_list is set correctly"
      ansible.builtin.assert:
        that:
          - "item.gid is defined"
          - "item.gid is number"
          - "item.gid > 0"
        quiet: true
      loop: "{{ system_users_setup_group_list }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - "system_users_setup_group_list is defined"
        - "item.gid is defined"

    - name: "Assert | Test if item.state in system_users_setup_group_list is set correctly"
      ansible.builtin.assert:
        that:
          - "item.state is defined"
          - "item.state is string"
          - "item.state in [ 'absent', 'present' ]"
        quiet: true
      loop: "{{ system_users_setup_group_list }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - "system_users_setup_group_list is defined"
        - "item.state is defined"

    - name: "Assert | Test if item.system in system_users_setup_group_list is set correctly"
      ansible.builtin.assert:
        that:
          - "item.system is boolean"
        quiet: true
      loop: "{{ system_users_setup_group_list }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - "system_users_setup_group_list is defined"
        - "item.system is defined"

    - name: "Assert | Test if item.name in system_users_setup_user_list is set correctly"
      ansible.builtin.assert:
        that:
          - "item.name is defined"
          - "item.name is string"
        quiet: true
      loop: "{{ system_users_setup_user_list }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - "system_users_setup_user_list is defined"

    - name: "Assert | Test if item.cron_allow in system_users_setup_user_list is set correctly"
      ansible.builtin.assert:
        that:
          - "item.cron_allow is boolean"
        quiet: true
      loop: "{{ system_users_setup_user_list }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - "system_users_setup_user_list is defined"
        - "item.cron_allow is defined"

    - name: "Assert | Test if item.uid in system_users_setup_user_list is set correctly"
      ansible.builtin.assert:
        that:
          - "item.uid is number"
          - "item.uid >= 0"
        quiet: true
      loop: "{{ system_users_setup_user_list }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - "system_users_setup_user_list is defined"
        - "item.uid is defined"

    - name: "Assert | Test if item.authorized_keys in system_users_setup_user_list is set correctly"
      ansible.builtin.assert:
        that:
          - "item.authorized_keys is iterable"
        quiet: true
      loop: "{{ system_users_setup_user_list }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - "system_users_setup_user_list is defined"
        - "item.authorized_keys is defined"

    - name: "Assert | Test if item.manage_ssh_key in system_users_setup_user_list is set correctly"
      ansible.builtin.assert:
        that:
          - "item.manage_ssh_key is boolean"
        quiet: true
      loop: "{{ system_users_setup_user_list }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - "system_users_setup_user_list is defined"
        - "item.manage_ssh_key is defined"

    - name: "Assert | Test if item.update_password in system_users_setup_user_list is set correctly"
      ansible.builtin.assert:
        that:
          - "item.update_password in [ 'always', 'on_create' ]"
        quiet: true
      loop: "{{ system_users_setup_user_list }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - "system_users_setup_user_list is defined"
        - "item.update_password is defined"

    - name: "Assert | Test if item.exipres in system_users_setup_user_list is set correctly"
      ansible.builtin.assert:
        that:
          - "item.expires is number"
          - "item.expires >= -1"
        quiet: true
      loop: "{{ system_users_setup_user_list }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - "system_users_setup_user_list is defined"
        - "item.expires is defined"

    - name: "Assert | Test if item.password_validity_days in system_users_setup_user_list is set correctly"
      ansible.builtin.assert:
        that:
          - "item.password_validity_days is number"
          - "item.password_validity_days >= -1"
        quiet: true
      loop: "{{ system_users_setup_user_list }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - "system_users_setup_user_list is defined"
        - "item.password_validity_days is defined"

    - name: "Assert | Test if item.system in system_users_setup_user_list is set correctly"
      ansible.builtin.assert:
        that:
          - "item.system is boolean"
        quiet: true
      loop: "{{ system_users_setup_user_list }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - "system_users_setup_user_list is defined"
        - "item.system is defined"

...
