---
system_dnf_setup_versionlock_use: false
system_dnf_setup_versionlock_packages: []

system_dnf_setup_automatic_use: false

# [commands]
system_dnf_setup_automatic_apply_updates: true
system_dnf_setup_automatic_download_updates: true
system_dnf_setup_automatic_upgrade_type: "security"
system_dnf_setup_automatic_random_sleep: 300

# [emitters]
system_dnf_setup_automatic_emit_via: "stdio"
system_dnf_setup_automatic_system_name: "{{ ansible_nodename }}"

# [command]
system_dnf_setup_automatic_command_format: "cat"
system_dnf_setup_automatic_stdin_format: "{body}"

# [command_email]
system_dnf_setup_automatic_email_command_format: "mail -s {subject} -r {email_from} {email_to}"
system_dnf_setup_automatic_email_stdin_format: "{body}"

# [email]
system_dnf_setup_automatic_email_from: "root"
system_dnf_setup_automatic_email_to: "root"
system_dnf_setup_automatic_email_host: "localhost"

# [base]

# this dict can be used to override arbitrary settings from dnf.conf
system_dnf_setup_automatic_base_overrides: {}

# Reboot
system_dnf_setup_automatic_reboot: false
system_dnf_setup_automatic_reboot_dependencies: yum-utils
system_dnf_setup_automatic_reboot_oncalendar: "03:00"
system_dnf_setup_automatic_reboot_accuracysec: "15s"
system_dnf_setup_automatic_reboot_description: "dnf-automatic-reboot"
system_dnf_setup_automatic_reboot_execstart: "/bin/bash -c '/bin/needs-restarting -r || /sbin/reboot'"

...
