---
- name: "Assert | Ensure __role_name is defined"
  ansible.builtin.assert:
    that:
      - "__role_name is defined"
      - "__role_name is string"
      - "__role_name | length > 0"
      # Make sure you can't forget to replace the role name
      - "__role_name != ['temp', 'late'] | join('')"

- name: "Assert | Setup specific vars"
  when: __role_action == "setup"
  block:

    - name: "Assert | Test system_kernel_setup_version"
      ansible.builtin.assert:
        that:
          - "system_kernel_setup_version is defined"
          - "system_kernel_setup_version is string"
          - "system_kernel_setup_version is not none"
        quiet: true

    - name: "Assert | Test system_kernel_setup_build_location"
      ansible.builtin.assert:
        that:
          - "system_kernel_setup_build_location is defined"
          - "system_kernel_setup_build_location is string"
          - "system_kernel_setup_build_location is not none"
        quiet: true

    - name: "Assert | Test system_kernel_setup_parameters"
      ansible.builtin.assert:
        that:
          - "system_kernel_setup_parameters is iterable"
        quiet: true
      when: "system_kernel_setup_parameters is defined"

    - name: "Assert | Test item in system_kernel_setup_parameters"
      ansible.builtin.assert:
        that:
          - "item.name is defined"
          - "item.name is string"
          - "item.name is not none"
          - "item.value is defined"
          - "item.value is string"
          - item.value in [ 'y', 'n', 'm' ]
        quiet: true
      loop: "{{ system_kernel_setup_parameters }}"
      loop_control:
        label: "{{ item.name }}"
      when: "system_kernel_setup_parameters is defined"

...
