---
# These settings are required in postfix.
system_postfix_setup_myhostname: "{{ ansible_facts['fqdn'] }}"
system_postfix_setup_mydomain: "{{ ansible_facts.domain | default('localdomain', true) }}"
system_postfix_setup_myorigin: "{{ ansible_facts.domain | default('localdomain', true) }}"

# To "listen" on public interfaces, set inet_interfaces to something like
# "all" or the name of the interface, such as "eth0".
system_postfix_setup_inet_interfaces: "loopback-only"

# Enable IPv4, and IPv6 if supported - if IPV4 only set to ipv4
system_postfix_setup_inet_protocols: "all"

# Set a banner
system_postfix_setup_banner: "$myhostname ESMTP $mail_name"

# The distination tells Postfix what mails to accept mail for.
# system_postfix_setup_mydestination: $mydomain, $myhostname, localhost.$mydomain, localhost

# To accept email from other machines, set the mynetworks to something like
# "- 192.168.0.0/24".
system_postfix_setup_mynetworks:
  - "127.0.0.0/8"

system_postfix_setup_daemon_directory: "/usr/lib/postfix/sbin"
system_postfix_setup_group: ""
system_postfix_setup_service: "postfix"

# These settings change the role of the postfix server to a relay host.
# system_postfix_setup_relay_domains: "$mydestination"

# If you want to forward emails to another central relay server, set relayhost.
# use brackets to sent to the A-record of the relayhost.
# system_postfix_setup_relayhost: "[relay.example.com]"

# Set the restrictions for receiving mails.
system_postfix_setup_smtpd_recipient_restrictions:
  - "permit_mynetworks"
  - "permit_sasl_authenticated"
  - "reject_unauth_destination"
  - "reject_invalid_hostname"
  - "reject_non_fqdn_hostname"
  - "reject_non_fqdn_sender"
  - "reject_non_fqdn_recipient"
  - "reject_unknown_sender_domain"
  - "reject_unknown_recipient_domain"
  - "reject_rbl_client sbl.spamhaus.org"
  - "reject_rbl_client cbl.abuseat.org"
  - "reject_rbl_client dul.dnsbl.sorbs.net"
  - "permit"

system_postfix_setup_smtpd_sender_restrictions:
  - "permit_sasl_authenticated"
  - "permit_mynetworks"
  - "warn_if_reject reject_non_fqdn_sender"
  - "reject_unknown_sender_domain"
  - "reject_unauth_pipelining"
  - "permit"

system_postfix_setup_smtpd_relay_restrictions:
  - "permit_mynetworks"
  - "permit_sasl_authenticated"
  - "reject_unauth_destination"

# The default SMTP TLS security level for the Postfix SMTP client
# Valid values are: dane, encrypt, fingerprint, may, none, secure, verify
system_postfix_setup_smtp_tls_security_level: none

# To enable spamassassin, ensure spamassassin is installed,
# system_postfix_setup_spamassassin: enabled
# system_postfix_setup_spamassassin_user: spamd

# To enable clamav, ensure clamav is installed,
# system_postfix_setup_clamav: enabled

# You can configure aliases here. Typically redirecting `root` is a good plan.
# system_postfix_setup_aliases:
#   - name: root
#     destination:

# You can configure sender access controls here.
# system_postfix_setup_sender_access:
#   - domain: gooddomain.com
#     action: OK
#   - domain: baddomain.com
#     action: REJECT

# You can configure recipient access controls here.
# system_postfix_setup_recipient_access:
#   - domain: gooddomain.com
#     action: OK
#   - domain: baddomain.com
#     action: REJECT

# You can disable SSL/TLS versions here.
# system_postfix_setup_tls_protocols: '!SSLv2, !SSLv3, !TLSv1, !TLSv1.1'

# You can supply a transport_maps Jinja2 template here
# system_postfix_setup_transport_maps_template: /path/to/transport.j2

# You can supply a header_checks Jinja2 template here
# system_postfix_setup_header_checks_template: /path/to/header_checks.j2

# Whether or not to use the local biff service.
# system_postfix_setup_biff: yes

# With locally submitted mail, append the string ".$mydomain" to addresses that have no ".domain" information
# system_postfix_setup_append_dot_mydomain: no

# The alias databases that are used for local(8) delivery
# system_postfix_setup_alias_maps: "hash:/etc/aliases"

# A prefix that the virtual(8) delivery agent prepends to all pathname results from $virtual_mailbox_maps table lookups.
# system_postfix_setup_virtual_mailbox_base: /var/mail

# Optional lookup tables with all valid addresses in the domains that match $virtual_mailbox_domains.
# system_postfix_setup_virtual_mailbox_maps: mysql:/etc/postfix/mysql-virtual_mailbox_maps.cf

# Postfix is final destination for the specified list of domains; mail is delivered via the $virtual_transport mail delivery transport
# system_postfix_setup_virtual_mailbox_domains: "$virtual_mailbox_maps"

# Postfix is final destination for specified list virtual alias domains, domains for all addresses aliased to addresses in local or remote domains.
# system_postfix_setup_virtual_alias_domains: "$virtual_alias_maps"

# Optional lookup tables that alias specific mail addresses or domains to other local or remote address.
# system_postix__setupvirtual_alias_maps: "$virtual_maps"

# Lookup tables with the per-recipient user ID that the virtual(8) delivery agent uses while writing to the recipient's mailbox.
# system_postfix_setup_virtual_uid_maps: "static:2000"

# Lookup tables with the per-recipient group ID for virtual(8) mailbox delivery.
# system_postfix_setup_virtual_gid_maps: "static:2000"

# Enable SASL authentication in the Postfix SMTP server.
# system_postfix_setup_smtpd_sasl_auth_enable: yes

# The name of the Postfix SMTP server's local SASL authentication realm.
# system_postfix_setup_smtpd_sasl_local_domain: $myhostname

# Postfix SMTP server SASL security options; as of Postfix 2.3 the list available features depends on SASL implementation that is selected smtpd_sasl_type.
# system_postfix_setup_smtpd_sasl_security_options: noanonymous

# Report the SASL authenticated user name in the smtpd(8) Received message header.
# system_postfix_setup_smtpd_sasl_authenticated_header: yes

# Enable interoperability with remote SMTP clients that implement an obsolete version of the AUTH command (RFC 4954).
# system_postfix_setup_broken_sasl_auth_clients: no

# A file containing (PEM format) CA certificates of root CAs trusted to sign either remote SMTP client certificates or intermediate CA certificates.
# system_postfix_setup_smtpd_tls_CAfile: /etc/letsencrypt/live/smtp.syhosting.ch/chain.pem

# File with the Postfix SMTP server RSA certificate in PEM format.
# system_postfix_setup_smtpd_tls_cert_file: /etc/letsencrypt/live/smtp.syhosting.ch/cert.pem

# File with the Postfix SMTP server RSA private key in PEM format.
# system_postfix_setup_smtpd_tls_key_file: /etc/letsencrypt/live/smtp.syhosting.ch/privkey.pem

# Request Postfix SMTP server produces Received: message headers including info protocol and cipher used, remote SMTP client CN / client cert. issuer CN.
# system_postfix_setup_smtpd_tls_received_header: yes

# The SMTP TLS security level Postfix SMTP client;non-empty value specified, overrides obsol. params smtp_use_tls, smtp_enforce_tls, smtp_tls_enforce_peername.
# system_postfix_setup_smtpd_tls_security_level: may

# Ask a remote SMTP client for a client certificate.
# system_postfix_setup_smtpd_tls_ask_ccert: yes

# Enable additional Postfix SMTP server logging of TLS activity.
# system_postfix_setup_smtpd_tls_loglevel: 1

# Name of the file containing the optional Postfix SMTP server TLS session cache.
# system_postfix_setup_smtpd_tls_session_cache_database: btree:/var/lib/postfix/smtpd_tls_session_cache

# A file containing CA certificates of root CAs trusted to sign either remote SMTP server certificates or intermediate CA certificates.
# system_postfix_setup_smtp_tls_CAfile: /etc/letsencrypt/live/smtp.syhosting.ch/chain.pem

# File with the Postfix SMTP client RSA certificate in PEM format.
# system_postfix_setup_smtp_tls_cert_file: /etc/letsencrypt/live/smtp.syhosting.ch/cert.pem

# File with the Postfix SMTP client RSA private key in PEM format.
# system_postfix_setup_smtp_tls_key_file: /etc/letsencrypt/live/smtp.syhosting.ch/privkey.pem

# Name of the file containing the optional Postfix SMTP client TLS session cache.
# system_postfix_setup_smtp_tls_session_cache_database: btree:/var/lib/postfix/smtp_tls_session_cache

# The external entropy source for the in-memory tlsmgr(8) pseudo random number generator (PRNG) pool.
# system_postfix_setup_tls_random_source: dev:/dev/urandom

# TLS protocols accepted by the Postfix SMTP server with mandatory TLS encryption.
# system_postfix_setup_smtpd_tls_mandatory_protocols: TLSv1

# TLS protocols that the Postfix SMTP client will use with mandatory TLS encryption.
# system_postfix_setup_smtp_tls_mandatory_protocols: TLSv1

# The default mail delivery transport and next-hop destination for final delivery to domains listed with $virtual_mailbox_domains.
# system_postfix_setup_virtual_transport: maildrop1

# Optional pathname of a mailbox file relative to a local(8) user's home directory.
# system_postfix_setup_home_mailbox: Maildir/

# The maximal size in bytes of a message, including envelope information.
# system_postfix_setup_message_size_limit: 10240000

# Require that a remote SMTP client introduces itself with the HELO or EHLO command before sending the MAIL
# command or other commands that require EHLO negotiation.
# system_postfix_setup_smtpd_helo_required: no

# The time unit over which client connection rates and other rates are calculated.
# system_postfix_setup_anvil_rate_time_unit: 60s

# The maximal number of connection attempts any client is allowed to make to this service per time unit.
# system_postfix_setup_smtpd_client_connection_rate_limit: 10

# How many simultaneous connections any client is allowed to make to this service.
# system_postfix_setup_smtpd_client_connection_count_limit: 10

# Consider a bounce message as undeliverable, when delivery fails with a temporary error, and the time in the queue has reached the bounce_queue_lifetime limit.
# system_postfix_setup_bounce_queue_lifetime: 5d

# The location of Postfix README files that describe how to build, configure or operate a specific Postfix subsystem or feature.
# system_postfix_setup_readme_directory: /usr/share/doc/postfix

# The location of Postfix HTML, configure or operate a specific Postfix subsystem or feature.
# system_postfix_setup_html_directory: /usr/share/doc/postfix/html

...
