---
selinux_state: "{{ system_selinux_state }}"
selinux_policy: "{{ system_selinux_policy }}"

# Set up empty lists for SELinux changes.
selinux_booleans: "{{ system_selinux_booleans | default([]) }}"
selinux_fcontexts: "{{ system_selinux_fcontexts | default([]) }}"
selinux_logins: "{{ system_selinux_logins | default([]) }}"
selinux_ports: "{{ system_selinux_ports | default([]) }}"
selinux_restore_dirs: "{{ system_selinux_restore_dirs | default([]) }}"

# Purging local modifications is disabled by default.
selinux_all_purge: "{{ system_selinux_all_purge | default('no') }}"
selinux_booleans_purge: "{{ system_selinux_booleans_purge | default('no') }}"
selinux_fcontexts_purge: "{{ system_selinux_fcontexts_purge | default('no') }}"
selinux_ports_purge: "{{ system_selinux_ports_purge | default('no') }}"
selinux_logins_purge: "{{ system_selinux_logins_purge | default('no') }}"

...
