---
- name: "Ensure __role_name is defined"
  ansible.builtin.assert:
    that:
      - "__role_name is defined"
      - "__role_name is string"
      - "__role_name | length > 0"
      # Make sure you can't forget to replace the role name
      - "__role_name != ['temp', 'late'] | join('')"

- name: "Assert | Assert setup specific vars"
  when: __role_action == "setup"
  block:
    - name: "Assert | Test system_motd_setup_msg"
      ansible.builtin.assert:
        that:
          - "system_motd_setup_msg is defined"
          - "system_motd_setup_msg is string"
        quiet: true

# - name: "Assert | Assert setup specific vars"
#   when: __role_action == "upstream"
#   block:

...
