---
galaxy_info:
  author: MTO79
  role_name: system_rhc
  description: Role to manage RH subscription management and Insights
  license: MIT
  min_ansible_version: "2.11.0"
  standalone: true

  platforms: []

  galaxy_tags:
    - mto79
    - system
    - linux
    - subscription
    - insights

dependencies: []

...
