---
galaxy_info:
  author: Marc Ouwerkerk.
  role_name: system_timesync
  description: Install and configure timesync and its required libraries on your system.
  license: Apache-2.0
  min_ansible_version: "2.10"
  standalone: true

  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - timesync
    - system

dependencies: []

...
