---
- name: "Setup | Run the insights-client --compliance"
  ansible.builtin.command:
    cmd: "insights-client --compliance"
  become: true
  register: "_system_openscap_setup_run_insights_compliance"
  changed_when: false
  failed_when: false

- name: "Setup | Display result from running the insights client"
  ansible.builtin.debug:
    var: "_system_openscap_setup_run_insights_compliance"

...
