---
#
# GitHub Actions workflow.
#
# Automatically Test with Molecule the "epel" system role.
#
name: Molecule Test Epel

on:
  push:
    branches:
      - main
    paths:
      - "roles/epel/**"
      - ".github/workflows/molecule_epel.yml"
    workflow_dispatch:

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies.
        run: pip3 install -r requirements.txt

      - name: Install Ansible dependencies.
        run: ansible-galaxy install -r requirements.yml

      - name: Run molecule
        run: "molecule test"

...
